name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up JDK (Android requires Java 17 for modern Gradle/SDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set up Gradle (system installation, since you don’t have gradlew)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      # 4. Build Debug APK
      - name: Build Debug APK
        run: gradle assembleDebug

      # 5. Upload APK to workflow artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
